name: 'JS Test Action'
description: 'Read repository info'
author: 'Michael Henderson'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
    
runs:
  using: node12
  main: 'dist/index.js'
